kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role
rules:
  - apiGroups: ['*']
    resources: 
      - services
      - pods
      - deployments
      - replicasets
    verbs: 
      - list
      - get