kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-role-binding
subjects:
  - kind: User
    name: user
roleRef:
  kind: Role
  name: user-role
  apiGroup: rbac.authorization.k8s.io